application: two-rooms
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico

- url: /css/(.*)
  static_files: static/css/\1
  upload: static/css/(.*)

- url: /js/(.*)
  static_files: static/js/\1
  upload: static/js/(.*)

- url: /partials/(.*)
  static_files: static/partials/\1
  upload: static/partials/(.*)

- url: /sound/(.*)
  static_files: static/sound/\1
  upload: static/sound/(.*)

- url: /img/(.*)
  static_files: static/img/\1
  upload: static/img/(.*)

- url: /bower_components/(.*)
  static_files: static/bower_components/\1
  upload: static/bower_components/(.*)

- url: /
  static_files: static/index.html
  upload: static/index.html

libraries:
- name: webapp2
  version: "2.5.2"
